# Generated by Django 4.2.4 on 2023-09-01 11:03

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default=None, max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_des', tinymce.models.HTMLField()),
                ('job_image', models.ImageField(default='job/jobs-1.jpg', null=True, upload_to='job/')),
                ('job_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='job_title', unique=True)),
            ],
        ),
    ]
