# Generated by Django 4.2.4 on 2023-09-04 07:07

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Internship')], default=None, max_length=1, null=True)),
                ('job_des', tinymce.models.HTMLField(blank=True, null=True)),
                ('salary', models.CharField(max_length=20)),
                ('company', models.CharField(default=None, max_length=100)),
                ('company_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('last_update', models.DateField()),
                ('job_image', models.ImageField(default='job/jobs-1.jpg', upload_to='job/')),
                ('job_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='job_title', unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
