# Generated by Django 4.2.4 on 2023-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
