# Generated by Django 4.2.4 on 2023-09-06 07:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='company-job_title', unique=True),
        ),
    ]
