# Generated by Django 4.2.4 on 2023-09-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_update',
        ),
    ]
