# Generated by Django 4.2.4 on 2023-08-18 12:08

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course_des', tinymce.models.HTMLField()),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Beginner', max_length=50)),
                ('course_duration', models.CharField(max_length=100)),
                ('course_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_title', unique=True)),
            ],
        ),
    ]
