# Generated by Django 4.2.4 on 2023-08-18 12:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dx6e8kwgl/image/upload/v1692361632/courses/courses-1_wgmii9.jpg', max_length=255, verbose_name='image'),
        ),
    ]
