# Generated by Django 4.2.4 on 2023-08-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courses_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default='course/courses-1.jpg', null=True, upload_to='corse/'),
        ),
    ]
