# Generated by Django 4.2.4 on 2023-08-29 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='profile/profile-default.jpg', null=True, upload_to='profile/')),
                ('profile_desc', models.TextField(blank=True, max_length=250)),
                ('institution', models.CharField(blank=True, max_length=50)),
                ('resume', models.FileField(default='resume/resume.pdf', null=True, upload_to='resume/')),
                ('resume_data', models.TextField(default='RESUME', max_length=3000, null=True)),
                ('skills', models.CharField(max_length=250)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
